ext doc|docx|odt|rtf|epub|pdf|csv|tsv|xls|xlsx|ods|xlsm|docxf|oform|vsdx|vsdm|pptx|ppt|odp, flag f = onlyoffice-desktopeditors "$@"
ext zip = unzip "$@" -d "${@%.zip}"
ext txt|md|log = nvim -c "set wrap" "$@"
ext conf|cnf|yml|yaml|json = nvim "$@"
ext js|css|html|htm|php|scss|sass = nvim "$@"
ext cs|xml|xaml|razor|csproj|sln|slnx|asp|aspx = nvim "$@"
mime ^text = nvim -c "set wrap" "$@"
ext svg = inkview "$@"
mime ^image, has feh,       X, flag f, !ext gif = feh -- "$@"
